[2022-06-19 16:54:13,890] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl scheduled__2022-06-18T00:00:00+00:00 [queued]>
[2022-06-19 16:54:13,900] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl scheduled__2022-06-18T00:00:00+00:00 [queued]>
[2022-06-19 16:54:13,901] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-19 16:54:13,901] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-06-19 16:54:13,901] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-19 16:54:13,921] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): my_etl> on 2022-06-18 00:00:00+00:00
[2022-06-19 16:54:13,926] {standard_task_runner.py:52} INFO - Started process 306 to run task
[2022-06-19 16:54:13,930] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'my_etl', 'scheduled__2022-06-18T00:00:00+00:00', '--job-id', '207', '--raw', '--subdir', 'DAGS_FOLDER/test-dag.py', '--cfg-path', '/tmp/tmprlrph81g', '--error-file', '/tmp/tmpwtajdglp']
[2022-06-19 16:54:13,931] {standard_task_runner.py:80} INFO - Job 207: Subtask my_etl
[2022-06-19 16:54:14,004] {task_command.py:370} INFO - Running <TaskInstance: test.my_etl scheduled__2022-06-18T00:00:00+00:00 [running]> on host 6f61ba935082
[2022-06-19 16:54:14,125] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=my_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-06-18T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-06-18T00:00:00+00:00
[2022-06-19 16:54:27,430] {logging_mixin.py:115} INFO -                                                 title  ...                                                url
0                 newSoftware Engineer - Intern/Co-op  ...  https://ca.indeed.com/rc/clk?jk=0ee1559c24a34e...
1                      newSoftware Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=ff663ba3d6b730...
2                         Software Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=9868590178c109...
3                           Software Developer Intern  ...  https://ca.indeed.com/rc/clk?jk=92e75e59e3c0a0...
4   Summer Intern: Professional Services Software ...  ...  https://ca.indeed.com/rc/clk?jk=58bb07dfc3229f...
5            Software Developer Intern, MS, Fall 2022  ...  https://ca.indeed.com/rc/clk?jk=f0c2273cc6ed69...
6                         Software Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=0793d983ef7a8b...
7                         Web Developer Summer Intern  ...  https://ca.indeed.com/company/Vaughan-Public-L...
8             Software Development Engineering Intern  ...  https://ca.indeed.com/rc/clk?jk=b37f5967ce21e3...
9                          Front End Developer Intern  ...  https://ca.indeed.com/company/RatherME-Inc./jo...
10  newSoftware Developer - User Experience (Inter...  ...  https://ca.indeed.com/rc/clk?jk=f561aa19396f07...
11                               WEB DEVELOPER INTERN  ...  https://ca.indeed.com/rc/clk?jk=a4d8dda65bbd8b...
12                          Intern, Software Engineer  ...  https://ca.indeed.com/rc/clk?jk=344a8a2ea0b60d...
13                 Software Development Intern - Dash  ...  https://ca.indeed.com/rc/clk?jk=18d2d9e3922781...
14              Fall 2022 - Software Developer Intern  ...  https://ca.indeed.com/rc/clk?jk=fb88c3258de70b...

[15 rows x 6 columns]
[2022-06-19 16:54:27,432] {taskinstance.py:1889} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 171, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 189, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/job_etl.py", line 96, in run_job_etl
    conn = psycopg2.connect(conn_string)
  File "/home/airflow/.local/lib/python3.7/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?

[2022-06-19 16:54:27,444] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=test, task_id=my_etl, execution_date=20220618T000000, start_date=20220619T165413, end_date=20220619T165427
[2022-06-19 16:54:27,479] {standard_task_runner.py:97} ERROR - Failed to execute job 207 for task my_etl (connection to server at "localhost" (127.0.0.1), port 5432 failed: Connection refused
	Is the server running on that host and accepting TCP/IP connections?
connection to server at "localhost" (::1), port 5432 failed: Cannot assign requested address
	Is the server running on that host and accepting TCP/IP connections?
; 306)
[2022-06-19 16:54:27,499] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-06-19 16:54:27,546] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
