[2022-07-08 21:21:48,719] {processor.py:153} INFO - Started process (PID=100) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:21:48,719] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:21:48,719] {logging_mixin.py:115} INFO - [2022-07-08 21:21:48,719] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:21:55,936] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:21:55,979] {logging_mixin.py:115} INFO - [2022-07-08 21:21:55,979] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:21:56,108] {logging_mixin.py:115} INFO - [2022-07-08 21:21:56,108] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:21:56,200] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 7.484 seconds
[2022-07-08 21:22:26,274] {processor.py:153} INFO - Started process (PID=132) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:22:26,286] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:22:26,287] {logging_mixin.py:115} INFO - [2022-07-08 21:22:26,286] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:22:26,588] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:22:26,614] {logging_mixin.py:115} INFO - [2022-07-08 21:22:26,613] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:22:26,633] {logging_mixin.py:115} INFO - [2022-07-08 21:22:26,633] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:22:26,655] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.385 seconds
[2022-07-08 21:22:56,738] {processor.py:153} INFO - Started process (PID=152) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:22:56,752] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:22:56,753] {logging_mixin.py:115} INFO - [2022-07-08 21:22:56,753] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:22:57,060] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:22:57,083] {logging_mixin.py:115} INFO - [2022-07-08 21:22:57,083] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:22:57,104] {logging_mixin.py:115} INFO - [2022-07-08 21:22:57,104] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:22:57,128] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.394 seconds
[2022-07-08 21:23:27,208] {processor.py:153} INFO - Started process (PID=182) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:23:27,219] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:23:27,219] {logging_mixin.py:115} INFO - [2022-07-08 21:23:27,219] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:23:27,493] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:23:27,516] {logging_mixin.py:115} INFO - [2022-07-08 21:23:27,515] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:23:27,536] {logging_mixin.py:115} INFO - [2022-07-08 21:23:27,536] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:23:27,555] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.351 seconds
[2022-07-08 21:23:57,641] {processor.py:153} INFO - Started process (PID=211) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:23:57,644] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:23:57,645] {logging_mixin.py:115} INFO - [2022-07-08 21:23:57,644] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:23:57,955] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:23:57,981] {logging_mixin.py:115} INFO - [2022-07-08 21:23:57,981] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:23:58,001] {logging_mixin.py:115} INFO - [2022-07-08 21:23:58,001] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:23:58,011] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.374 seconds
[2022-07-08 21:24:28,094] {processor.py:153} INFO - Started process (PID=231) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:24:28,103] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:24:28,103] {logging_mixin.py:115} INFO - [2022-07-08 21:24:28,103] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:24:28,404] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:24:28,425] {logging_mixin.py:115} INFO - [2022-07-08 21:24:28,425] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:24:28,447] {logging_mixin.py:115} INFO - [2022-07-08 21:24:28,446] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:24:28,496] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.406 seconds
[2022-07-08 21:24:58,577] {processor.py:153} INFO - Started process (PID=260) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:24:58,578] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:24:58,578] {logging_mixin.py:115} INFO - [2022-07-08 21:24:58,578] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:24:58,868] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:24:58,889] {logging_mixin.py:115} INFO - [2022-07-08 21:24:58,888] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:24:58,911] {logging_mixin.py:115} INFO - [2022-07-08 21:24:58,911] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:24:58,931] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.358 seconds
[2022-07-08 21:25:29,011] {processor.py:153} INFO - Started process (PID=290) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:25:29,027] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:25:29,028] {logging_mixin.py:115} INFO - [2022-07-08 21:25:29,028] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:25:29,310] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:25:29,337] {logging_mixin.py:115} INFO - [2022-07-08 21:25:29,336] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:25:29,358] {logging_mixin.py:115} INFO - [2022-07-08 21:25:29,357] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:25:29,382] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.375 seconds
[2022-07-08 21:25:59,462] {processor.py:153} INFO - Started process (PID=310) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:25:59,476] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:25:59,477] {logging_mixin.py:115} INFO - [2022-07-08 21:25:59,477] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:25:59,772] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:25:59,796] {logging_mixin.py:115} INFO - [2022-07-08 21:25:59,795] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:25:59,818] {logging_mixin.py:115} INFO - [2022-07-08 21:25:59,818] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:25:59,837] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.379 seconds
[2022-07-08 21:26:29,914] {processor.py:153} INFO - Started process (PID=339) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:26:29,915] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:26:29,915] {logging_mixin.py:115} INFO - [2022-07-08 21:26:29,915] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:26:30,205] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:26:30,228] {logging_mixin.py:115} INFO - [2022-07-08 21:26:30,227] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:26:30,247] {logging_mixin.py:115} INFO - [2022-07-08 21:26:30,247] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:26:30,259] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.349 seconds
[2022-07-08 21:27:00,358] {processor.py:153} INFO - Started process (PID=368) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:27:00,375] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:27:00,376] {logging_mixin.py:115} INFO - [2022-07-08 21:27:00,376] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:27:00,667] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:27:00,691] {logging_mixin.py:115} INFO - [2022-07-08 21:27:00,690] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:27:00,711] {logging_mixin.py:115} INFO - [2022-07-08 21:27:00,711] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:27:00,739] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.385 seconds
[2022-07-08 21:27:30,818] {processor.py:153} INFO - Started process (PID=388) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:27:30,818] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:27:30,819] {logging_mixin.py:115} INFO - [2022-07-08 21:27:30,819] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:27:31,129] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:27:31,156] {logging_mixin.py:115} INFO - [2022-07-08 21:27:31,156] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:27:31,176] {logging_mixin.py:115} INFO - [2022-07-08 21:27:31,176] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:27:31,213] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.398 seconds
[2022-07-08 21:28:01,296] {processor.py:153} INFO - Started process (PID=416) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:28:01,308] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:28:01,309] {logging_mixin.py:115} INFO - [2022-07-08 21:28:01,309] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:28:01,605] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:28:01,631] {logging_mixin.py:115} INFO - [2022-07-08 21:28:01,630] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:28:01,652] {logging_mixin.py:115} INFO - [2022-07-08 21:28:01,652] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:28:01,679] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.387 seconds
[2022-07-08 21:28:31,758] {processor.py:153} INFO - Started process (PID=445) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:28:31,759] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:28:31,760] {logging_mixin.py:115} INFO - [2022-07-08 21:28:31,760] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:28:32,064] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:28:32,087] {logging_mixin.py:115} INFO - [2022-07-08 21:28:32,087] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:28:32,115] {logging_mixin.py:115} INFO - [2022-07-08 21:28:32,115] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:28:32,160] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.405 seconds
[2022-07-08 21:29:02,247] {processor.py:153} INFO - Started process (PID=465) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:29:02,248] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:29:02,248] {logging_mixin.py:115} INFO - [2022-07-08 21:29:02,248] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:29:02,556] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:29:02,581] {logging_mixin.py:115} INFO - [2022-07-08 21:29:02,581] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:29:02,602] {logging_mixin.py:115} INFO - [2022-07-08 21:29:02,602] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:29:02,618] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.375 seconds
[2022-07-08 21:29:32,701] {processor.py:153} INFO - Started process (PID=494) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:29:32,708] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:29:32,708] {logging_mixin.py:115} INFO - [2022-07-08 21:29:32,708] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:29:33,016] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:29:33,043] {logging_mixin.py:115} INFO - [2022-07-08 21:29:33,042] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:29:33,066] {logging_mixin.py:115} INFO - [2022-07-08 21:29:33,066] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:29:33,084] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.387 seconds
[2022-07-08 21:30:03,164] {processor.py:153} INFO - Started process (PID=521) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:30:03,165] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:30:03,165] {logging_mixin.py:115} INFO - [2022-07-08 21:30:03,165] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:30:03,464] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:30:03,491] {logging_mixin.py:115} INFO - [2022-07-08 21:30:03,491] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:30:03,515] {logging_mixin.py:115} INFO - [2022-07-08 21:30:03,515] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2023-06-29T00:00:00+00:00
[2022-07-08 21:30:03,541] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.381 seconds
[2022-07-08 21:30:11,183] {processor.py:153} INFO - Started process (PID=525) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:30:11,183] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:30:11,184] {logging_mixin.py:115} INFO - [2022-07-08 21:30:11,184] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:30:11,489] {logging_mixin.py:115} INFO - [2022-07-08 21:30:11,476] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
ModuleNotFoundError: No module named 'SLTrack'
[2022-07-08 21:30:11,489] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:30:11,537] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.359 seconds
[2022-07-08 21:30:41,614] {processor.py:153} INFO - Started process (PID=554) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:30:41,614] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:30:41,614] {logging_mixin.py:115} INFO - [2022-07-08 21:30:41,614] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:30:42,015] {logging_mixin.py:115} INFO - [2022-07-08 21:30:42,014] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
ModuleNotFoundError: No module named 'SLTrack'
[2022-07-08 21:30:42,015] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:30:42,045] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.434 seconds
[2022-07-08 21:31:12,121] {processor.py:153} INFO - Started process (PID=582) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:31:12,122] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:31:12,123] {logging_mixin.py:115} INFO - [2022-07-08 21:31:12,123] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:31:12,408] {logging_mixin.py:115} INFO - [2022-07-08 21:31:12,408] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
ModuleNotFoundError: No module named 'SLTrack'
[2022-07-08 21:31:12,408] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:31:12,436] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.319 seconds
[2022-07-08 21:31:14,132] {processor.py:153} INFO - Started process (PID=586) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:31:14,132] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:31:14,133] {logging_mixin.py:115} INFO - [2022-07-08 21:31:14,133] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:31:14,448] {logging_mixin.py:115} INFO - [2022-07-08 21:31:14,447] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
ModuleNotFoundError: No module named 'SLTrack'
[2022-07-08 21:31:14,448] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:31:14,497] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.369 seconds
[2022-07-08 21:31:44,541] {processor.py:153} INFO - Started process (PID=606) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:31:44,546] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:31:44,546] {logging_mixin.py:115} INFO - [2022-07-08 21:31:44,546] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:31:44,832] {logging_mixin.py:115} INFO - [2022-07-08 21:31:44,831] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
ModuleNotFoundError: No module named 'SLTrack'
[2022-07-08 21:31:44,832] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:31:44,861] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.323 seconds
[2022-07-08 21:32:14,951] {processor.py:153} INFO - Started process (PID=636) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:32:14,951] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:32:14,951] {logging_mixin.py:115} INFO - [2022-07-08 21:32:14,951] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:32:15,256] {logging_mixin.py:115} INFO - [2022-07-08 21:32:15,255] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
ModuleNotFoundError: No module named 'SLTrack'
[2022-07-08 21:32:15,256] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:32:15,286] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.337 seconds
[2022-07-08 21:32:45,368] {processor.py:153} INFO - Started process (PID=666) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:32:45,370] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:32:45,370] {logging_mixin.py:115} INFO - [2022-07-08 21:32:45,370] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:32:45,671] {logging_mixin.py:115} INFO - [2022-07-08 21:32:45,670] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
ModuleNotFoundError: No module named 'SLTrack'
[2022-07-08 21:32:45,671] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:32:45,693] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.330 seconds
[2022-07-08 21:32:51,403] {processor.py:153} INFO - Started process (PID=668) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:32:51,404] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:32:51,404] {logging_mixin.py:115} INFO - [2022-07-08 21:32:51,404] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:32:51,704] {logging_mixin.py:115} INFO - [2022-07-08 21:32:51,704] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
ModuleNotFoundError: No module named 'SLTrack'
[2022-07-08 21:32:51,704] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:32:51,735] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.336 seconds
[2022-07-08 21:33:21,808] {processor.py:153} INFO - Started process (PID=697) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:33:21,809] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:33:21,810] {logging_mixin.py:115} INFO - [2022-07-08 21:33:21,810] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:33:22,115] {logging_mixin.py:115} INFO - [2022-07-08 21:33:22,114] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
ModuleNotFoundError: No module named 'SLTrack'
[2022-07-08 21:33:22,115] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:33:22,143] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.339 seconds
[2022-07-08 21:33:52,221] {processor.py:153} INFO - Started process (PID=717) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:33:52,231] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:33:52,232] {logging_mixin.py:115} INFO - [2022-07-08 21:33:52,232] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:33:52,573] {logging_mixin.py:115} INFO - [2022-07-08 21:33:52,545] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 37, in <module>
    dag=dag
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 156, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 764, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py", line 196, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'my_etl' has already been added to the DAG
[2022-07-08 21:33:52,573] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:33:52,609] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.393 seconds
[2022-07-08 21:34:22,688] {processor.py:153} INFO - Started process (PID=746) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:34:22,688] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:34:22,689] {logging_mixin.py:115} INFO - [2022-07-08 21:34:22,689] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:34:22,969] {logging_mixin.py:115} INFO - [2022-07-08 21:34:22,967] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 37, in <module>
    dag=dag
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 156, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 764, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py", line 196, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'my_etl' has already been added to the DAG
[2022-07-08 21:34:22,969] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:34:22,992] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.309 seconds
[2022-07-08 21:34:53,070] {processor.py:153} INFO - Started process (PID=776) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:34:53,078] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:34:53,079] {logging_mixin.py:115} INFO - [2022-07-08 21:34:53,079] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:34:53,397] {logging_mixin.py:115} INFO - [2022-07-08 21:34:53,396] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 37, in <module>
    dag=dag
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 156, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 764, in __init__
    task_group.add(self)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/task_group.py", line 196, in add
    raise DuplicateTaskIdFound(f"{node_type} id '{key}' has already been added to the DAG")
airflow.exceptions.DuplicateTaskIdFound: Task id 'my_etl' has already been added to the DAG
[2022-07-08 21:34:53,397] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:34:53,434] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.367 seconds
[2022-07-08 21:34:57,086] {processor.py:153} INFO - Started process (PID=778) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:34:57,086] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:34:57,086] {logging_mixin.py:115} INFO - [2022-07-08 21:34:57,086] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:34:57,403] {logging_mixin.py:115} INFO - [2022-07-08 21:34:57,394] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 31, in <module>
    dag=dag
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 156, in __init__
    super().__init__(**kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 390, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 754, in __init__
    validate_key(task_id)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/helpers.py", line 64, in validate_key
    f"The key {k!r} has to be made of alphanumeric characters, dashes, "
airflow.exceptions.AirflowException: The key 'api request' has to be made of alphanumeric characters, dashes, dots and underscores exclusively
[2022-07-08 21:34:57,404] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:34:57,467] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.386 seconds
[2022-07-08 21:35:16,520] {processor.py:153} INFO - Started process (PID=798) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:35:16,520] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:35:16,521] {logging_mixin.py:115} INFO - [2022-07-08 21:35:16,521] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:35:16,823] {logging_mixin.py:115} INFO - [2022-07-08 21:35:16,822] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 40, in <module>
    api > load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 969, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): load_data>) is not an outlet
[2022-07-08 21:35:16,823] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:35:16,850] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.334 seconds
[2022-07-08 21:35:38,569] {processor.py:153} INFO - Started process (PID=818) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:35:38,583] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:35:38,584] {logging_mixin.py:115} INFO - [2022-07-08 21:35:38,584] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:35:38,892] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:35:38,955] {logging_mixin.py:115} INFO - [2022-07-08 21:35:38,954] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:35:38,977] {logging_mixin.py:115} INFO - [2022-07-08 21:35:38,977] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-29T00:00:00+00:00, run_after=2022-06-30T00:00:00+00:00
[2022-07-08 21:35:39,008] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.443 seconds
[2022-07-08 21:36:09,082] {processor.py:153} INFO - Started process (PID=838) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:36:09,100] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:36:09,101] {logging_mixin.py:115} INFO - [2022-07-08 21:36:09,101] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:36:09,408] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:36:09,429] {logging_mixin.py:115} INFO - [2022-07-08 21:36:09,429] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:36:09,452] {logging_mixin.py:115} INFO - [2022-07-08 21:36:09,452] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 21:36:09,467] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.389 seconds
[2022-07-08 21:36:39,543] {processor.py:153} INFO - Started process (PID=868) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:36:39,558] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:36:39,558] {logging_mixin.py:115} INFO - [2022-07-08 21:36:39,558] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:36:39,864] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:36:39,887] {logging_mixin.py:115} INFO - [2022-07-08 21:36:39,886] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:36:39,907] {logging_mixin.py:115} INFO - [2022-07-08 21:36:39,907] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 21:36:39,929] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.390 seconds
[2022-07-08 21:37:10,037] {processor.py:153} INFO - Started process (PID=899) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:37:10,038] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:37:10,038] {logging_mixin.py:115} INFO - [2022-07-08 21:37:10,038] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:37:10,326] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:37:10,348] {logging_mixin.py:115} INFO - [2022-07-08 21:37:10,348] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:37:10,375] {logging_mixin.py:115} INFO - [2022-07-08 21:37:10,375] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 21:37:10,398] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.366 seconds
[2022-07-08 21:37:40,477] {processor.py:153} INFO - Started process (PID=920) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:37:40,478] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:37:40,478] {logging_mixin.py:115} INFO - [2022-07-08 21:37:40,478] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:37:40,809] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:37:40,835] {logging_mixin.py:115} INFO - [2022-07-08 21:37:40,834] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:37:40,855] {logging_mixin.py:115} INFO - [2022-07-08 21:37:40,855] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 21:37:40,917] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.444 seconds
[2022-07-08 21:38:10,998] {processor.py:153} INFO - Started process (PID=949) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:38:11,006] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:38:11,007] {logging_mixin.py:115} INFO - [2022-07-08 21:38:11,006] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:38:11,350] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:38:11,381] {logging_mixin.py:115} INFO - [2022-07-08 21:38:11,381] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:38:11,401] {logging_mixin.py:115} INFO - [2022-07-08 21:38:11,401] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 21:38:11,426] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.432 seconds
[2022-07-08 21:38:40,503] {processor.py:153} INFO - Started process (PID=970) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:38:40,518] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:38:40,519] {logging_mixin.py:115} INFO - [2022-07-08 21:38:40,519] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:38:40,819] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:38:40,893] {logging_mixin.py:115} INFO - [2022-07-08 21:38:40,892] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:38:40,914] {logging_mixin.py:115} INFO - [2022-07-08 21:38:40,914] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 21:38:40,943] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.443 seconds
[2022-07-08 21:39:11,024] {processor.py:153} INFO - Started process (PID=1014) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:39:11,047] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:39:11,048] {logging_mixin.py:115} INFO - [2022-07-08 21:39:11,048] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:39:11,332] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:39:11,361] {logging_mixin.py:115} INFO - [2022-07-08 21:39:11,361] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:39:11,380] {logging_mixin.py:115} INFO - [2022-07-08 21:39:11,380] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 21:39:11,405] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.385 seconds
[2022-07-08 21:39:41,484] {processor.py:153} INFO - Started process (PID=1043) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:39:41,496] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:39:41,497] {logging_mixin.py:115} INFO - [2022-07-08 21:39:41,497] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:39:41,804] {logging_mixin.py:115} INFO - [2022-07-08 21:39:41,803] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:39:41,805] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:39:41,834] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.354 seconds
[2022-07-08 21:40:11,916] {processor.py:153} INFO - Started process (PID=1064) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:40:11,917] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:40:11,917] {logging_mixin.py:115} INFO - [2022-07-08 21:40:11,917] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:40:12,216] {logging_mixin.py:115} INFO - [2022-07-08 21:40:12,215] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:40:12,217] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:40:12,260] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.348 seconds
[2022-07-08 21:40:42,334] {processor.py:153} INFO - Started process (PID=1099) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:40:42,344] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:40:42,345] {logging_mixin.py:115} INFO - [2022-07-08 21:40:42,345] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:40:42,652] {logging_mixin.py:115} INFO - [2022-07-08 21:40:42,650] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:40:42,652] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:40:42,671] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.340 seconds
[2022-07-08 21:41:12,752] {processor.py:153} INFO - Started process (PID=1128) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:41:12,760] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:41:12,761] {logging_mixin.py:115} INFO - [2022-07-08 21:41:12,761] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:41:13,077] {logging_mixin.py:115} INFO - [2022-07-08 21:41:13,076] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:41:13,078] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:41:13,106] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.358 seconds
[2022-07-08 21:41:43,188] {processor.py:153} INFO - Started process (PID=1148) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:41:43,201] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:41:43,202] {logging_mixin.py:115} INFO - [2022-07-08 21:41:43,202] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:41:43,500] {logging_mixin.py:115} INFO - [2022-07-08 21:41:43,499] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:41:43,500] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:41:43,531] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.346 seconds
[2022-07-08 21:42:13,616] {processor.py:153} INFO - Started process (PID=1177) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:42:13,626] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:42:13,627] {logging_mixin.py:115} INFO - [2022-07-08 21:42:13,627] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:42:13,936] {logging_mixin.py:115} INFO - [2022-07-08 21:42:13,935] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:42:13,936] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:42:13,971] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.359 seconds
[2022-07-08 21:42:44,045] {processor.py:153} INFO - Started process (PID=1206) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:42:44,059] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:42:44,060] {logging_mixin.py:115} INFO - [2022-07-08 21:42:44,060] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:42:44,372] {logging_mixin.py:115} INFO - [2022-07-08 21:42:44,371] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:42:44,372] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:42:44,405] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.363 seconds
[2022-07-08 21:43:14,483] {processor.py:153} INFO - Started process (PID=1226) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:43:14,492] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:43:14,492] {logging_mixin.py:115} INFO - [2022-07-08 21:43:14,492] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:43:14,808] {logging_mixin.py:115} INFO - [2022-07-08 21:43:14,807] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:43:14,808] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:43:14,844] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.366 seconds
[2022-07-08 21:43:44,926] {processor.py:153} INFO - Started process (PID=1257) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:43:44,933] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:43:44,933] {logging_mixin.py:115} INFO - [2022-07-08 21:43:44,933] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:43:45,239] {logging_mixin.py:115} INFO - [2022-07-08 21:43:45,238] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:43:45,239] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:43:45,271] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.349 seconds
[2022-07-08 21:44:15,356] {processor.py:153} INFO - Started process (PID=1277) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:44:15,424] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:44:15,425] {logging_mixin.py:115} INFO - [2022-07-08 21:44:15,425] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:44:15,747] {logging_mixin.py:115} INFO - [2022-07-08 21:44:15,745] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:44:15,747] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:44:15,796] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.445 seconds
[2022-07-08 21:44:45,876] {processor.py:153} INFO - Started process (PID=1307) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:44:45,890] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:44:45,891] {logging_mixin.py:115} INFO - [2022-07-08 21:44:45,891] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:44:46,206] {logging_mixin.py:115} INFO - [2022-07-08 21:44:46,205] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:44:46,206] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:44:46,228] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.356 seconds
[2022-07-08 21:45:16,307] {processor.py:153} INFO - Started process (PID=1336) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:45:16,307] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:45:16,308] {logging_mixin.py:115} INFO - [2022-07-08 21:45:16,308] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:45:16,599] {logging_mixin.py:115} INFO - [2022-07-08 21:45:16,598] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:45:16,600] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:45:16,627] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.325 seconds
[2022-07-08 21:45:46,701] {processor.py:153} INFO - Started process (PID=1356) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:45:46,709] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:45:46,710] {logging_mixin.py:115} INFO - [2022-07-08 21:45:46,709] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:45:47,045] {logging_mixin.py:115} INFO - [2022-07-08 21:45:47,044] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:45:47,045] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:45:47,077] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.381 seconds
[2022-07-08 21:46:17,159] {processor.py:153} INFO - Started process (PID=1385) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:46:17,160] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:46:17,160] {logging_mixin.py:115} INFO - [2022-07-08 21:46:17,160] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:46:17,446] {logging_mixin.py:115} INFO - [2022-07-08 21:46:17,445] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:46:17,446] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:46:17,477] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.322 seconds
[2022-07-08 21:46:47,556] {processor.py:153} INFO - Started process (PID=1414) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:46:47,580] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:46:47,581] {logging_mixin.py:115} INFO - [2022-07-08 21:46:47,581] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:46:47,885] {logging_mixin.py:115} INFO - [2022-07-08 21:46:47,884] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:46:47,886] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:46:47,965] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.414 seconds
[2022-07-08 21:47:18,043] {processor.py:153} INFO - Started process (PID=1434) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:47:18,049] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:47:18,050] {logging_mixin.py:115} INFO - [2022-07-08 21:47:18,050] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:47:18,356] {logging_mixin.py:115} INFO - [2022-07-08 21:47:18,355] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:47:18,356] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:47:18,385] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.344 seconds
[2022-07-08 21:47:48,464] {processor.py:153} INFO - Started process (PID=1464) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:47:48,464] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:47:48,465] {logging_mixin.py:115} INFO - [2022-07-08 21:47:48,465] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:47:48,761] {logging_mixin.py:115} INFO - [2022-07-08 21:47:48,759] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:47:48,761] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:47:48,793] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.333 seconds
[2022-07-08 21:48:18,878] {processor.py:153} INFO - Started process (PID=1493) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:48:18,890] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:48:18,890] {logging_mixin.py:115} INFO - [2022-07-08 21:48:18,890] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:48:19,205] {logging_mixin.py:115} INFO - [2022-07-08 21:48:19,203] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:48:19,205] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:48:19,252] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.378 seconds
[2022-07-08 21:48:49,334] {processor.py:153} INFO - Started process (PID=1513) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:48:49,345] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:48:49,346] {logging_mixin.py:115} INFO - [2022-07-08 21:48:49,346] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:48:49,656] {logging_mixin.py:115} INFO - [2022-07-08 21:48:49,655] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:48:49,657] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:48:49,692] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.362 seconds
[2022-07-08 21:49:19,769] {processor.py:153} INFO - Started process (PID=1542) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:49:19,778] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:49:19,779] {logging_mixin.py:115} INFO - [2022-07-08 21:49:19,779] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:49:20,081] {logging_mixin.py:115} INFO - [2022-07-08 21:49:20,080] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:49:20,081] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:49:20,108] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.343 seconds
[2022-07-08 21:49:50,187] {processor.py:153} INFO - Started process (PID=1571) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:49:50,187] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:49:50,188] {logging_mixin.py:115} INFO - [2022-07-08 21:49:50,188] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:49:50,491] {logging_mixin.py:115} INFO - [2022-07-08 21:49:50,490] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:49:50,492] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:49:50,524] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.341 seconds
[2022-07-08 21:50:20,629] {processor.py:153} INFO - Started process (PID=1591) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:50:20,630] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:50:20,630] {logging_mixin.py:115} INFO - [2022-07-08 21:50:20,630] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:50:20,951] {logging_mixin.py:115} INFO - [2022-07-08 21:50:20,949] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:50:20,951] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:50:20,982] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.357 seconds
[2022-07-08 21:50:51,056] {processor.py:153} INFO - Started process (PID=1619) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:50:51,069] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:50:51,069] {logging_mixin.py:115} INFO - [2022-07-08 21:50:51,069] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:50:51,380] {logging_mixin.py:115} INFO - [2022-07-08 21:50:51,379] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:50:51,380] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:50:51,407] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.353 seconds
[2022-07-08 21:51:21,486] {processor.py:153} INFO - Started process (PID=1639) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:51:21,493] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:51:21,493] {logging_mixin.py:115} INFO - [2022-07-08 21:51:21,493] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:51:21,774] {logging_mixin.py:115} INFO - [2022-07-08 21:51:21,773] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:51:21,774] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:51:21,806] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.324 seconds
[2022-07-08 21:51:51,907] {processor.py:153} INFO - Started process (PID=1668) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:51:51,907] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:51:51,908] {logging_mixin.py:115} INFO - [2022-07-08 21:51:51,908] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:51:52,201] {logging_mixin.py:115} INFO - [2022-07-08 21:51:52,199] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 162, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 148, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:51:52,201] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:51:52,231] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.327 seconds
[2022-07-08 21:52:22,308] {processor.py:153} INFO - Started process (PID=1697) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:52:22,309] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:52:22,309] {logging_mixin.py:115} INFO - [2022-07-08 21:52:22,309] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:52:22,626] {logging_mixin.py:115} INFO - [2022-07-08 21:52:22,625] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 166, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 152, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:52:22,627] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:52:22,665] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.358 seconds
[2022-07-08 21:52:52,746] {processor.py:153} INFO - Started process (PID=1718) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:52:52,747] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:52:52,747] {logging_mixin.py:115} INFO - [2022-07-08 21:52:52,747] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:52:53,071] {logging_mixin.py:115} INFO - [2022-07-08 21:52:53,069] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 167, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 152, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:52:53,071] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:52:53,106] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.364 seconds
[2022-07-08 21:53:23,183] {processor.py:153} INFO - Started process (PID=1747) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:53:23,184] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:53:23,185] {logging_mixin.py:115} INFO - [2022-07-08 21:53:23,185] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:53:23,503] {logging_mixin.py:115} INFO - [2022-07-08 21:53:23,502] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 167, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 152, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:53:23,503] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:53:23,530] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.351 seconds
[2022-07-08 21:53:53,602] {processor.py:153} INFO - Started process (PID=1775) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:53:53,615] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:53:53,616] {logging_mixin.py:115} INFO - [2022-07-08 21:53:53,615] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:53:53,937] {logging_mixin.py:115} INFO - [2022-07-08 21:53:53,936] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 149
    df.rename(columns={f"{column}"}:f"{column.lower()}")
                                   ^
SyntaxError: invalid syntax
[2022-07-08 21:53:53,937] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:53:54,005] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.407 seconds
[2022-07-08 21:54:24,087] {processor.py:153} INFO - Started process (PID=1796) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:54:24,088] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:54:24,088] {logging_mixin.py:115} INFO - [2022-07-08 21:54:24,088] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:54:24,362] {logging_mixin.py:115} INFO - [2022-07-08 21:54:24,361] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 149
    df.rename(columns={f"{column}"}:f"{column.lower()}")
                                   ^
SyntaxError: invalid syntax
[2022-07-08 21:54:24,362] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:54:24,388] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.305 seconds
[2022-07-08 21:54:54,466] {processor.py:153} INFO - Started process (PID=1825) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:54:54,481] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:54:54,481] {logging_mixin.py:115} INFO - [2022-07-08 21:54:54,481] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:54:54,785] {logging_mixin.py:115} INFO - [2022-07-08 21:54:54,784] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 149
    df.rename(columns={f"{column}"}:f"{column.lower()}")
                                   ^
SyntaxError: invalid syntax
[2022-07-08 21:54:54,785] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:54:54,812] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.351 seconds
[2022-07-08 21:55:24,890] {processor.py:153} INFO - Started process (PID=1854) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:55:24,898] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:55:24,898] {logging_mixin.py:115} INFO - [2022-07-08 21:55:24,898] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:55:25,189] {logging_mixin.py:115} INFO - [2022-07-08 21:55:25,188] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 167, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 152, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:55:25,189] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:55:25,229] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.343 seconds
[2022-07-08 21:55:55,311] {processor.py:153} INFO - Started process (PID=1875) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:55:55,322] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:55:55,323] {logging_mixin.py:115} INFO - [2022-07-08 21:55:55,323] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:55:55,643] {logging_mixin.py:115} INFO - [2022-07-08 21:55:55,642] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 167, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 152, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:55:55,643] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:55:55,670] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.363 seconds
[2022-07-08 21:56:25,753] {processor.py:153} INFO - Started process (PID=1904) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:56:25,764] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:56:25,764] {logging_mixin.py:115} INFO - [2022-07-08 21:56:25,764] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:56:26,062] {logging_mixin.py:115} INFO - [2022-07-08 21:56:26,060] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 168, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 153, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:56:26,062] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:56:26,095] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.346 seconds
[2022-07-08 21:56:56,190] {processor.py:153} INFO - Started process (PID=1925) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:56:56,204] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:56:56,205] {logging_mixin.py:115} INFO - [2022-07-08 21:56:56,205] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:56:56,478] {logging_mixin.py:115} INFO - [2022-07-08 21:56:56,477] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 168, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 153, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:56:56,478] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:56:56,494] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.309 seconds
[2022-07-08 21:57:26,564] {processor.py:153} INFO - Started process (PID=1955) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:57:26,588] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:57:26,589] {logging_mixin.py:115} INFO - [2022-07-08 21:57:26,589] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:57:26,911] {logging_mixin.py:115} INFO - [2022-07-08 21:57:26,910] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 168, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 153, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:57:26,911] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:57:26,944] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.384 seconds
[2022-07-08 21:57:57,021] {processor.py:153} INFO - Started process (PID=1985) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:57:57,054] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:57:57,054] {logging_mixin.py:115} INFO - [2022-07-08 21:57:57,054] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:57:57,347] {logging_mixin.py:115} INFO - [2022-07-08 21:57:57,346] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 168, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 153, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:57:57,347] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:57:57,378] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.360 seconds
[2022-07-08 21:58:27,458] {processor.py:153} INFO - Started process (PID=2005) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:58:27,470] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:58:27,470] {logging_mixin.py:115} INFO - [2022-07-08 21:58:27,470] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:58:27,809] {logging_mixin.py:115} INFO - [2022-07-08 21:58:27,808] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 168, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 153, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:58:27,809] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:58:27,845] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.391 seconds
[2022-07-08 21:58:57,921] {processor.py:153} INFO - Started process (PID=2034) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:58:57,936] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:58:57,937] {logging_mixin.py:115} INFO - [2022-07-08 21:58:57,937] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:58:58,279] {logging_mixin.py:115} INFO - [2022-07-08 21:58:58,278] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 168, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 153, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:58:58,279] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:58:58,319] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.402 seconds
[2022-07-08 21:59:28,399] {processor.py:153} INFO - Started process (PID=2063) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:59:28,400] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:59:28,400] {logging_mixin.py:115} INFO - [2022-07-08 21:59:28,400] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:59:28,693] {logging_mixin.py:115} INFO - [2022-07-08 21:59:28,692] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 11, in <module>
    from SLTrack import api_call, load_satellite_data
  File "/opt/airflow/dags/SLTrack.py", line 168, in <module>
    load_satellite_data()
  File "/opt/airflow/dags/SLTrack.py", line 153, in load_satellite_data
    data = pd.read_json('/home/L/Programming/dataEng/spaceApp/spacTrackAPI/TLEData.json')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 207, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 614, in read_json
    return json_reader.read()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 748, in read
    obj = self._get_object_parser(self.data)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 770, in _get_object_parser
    obj = FrameParser(json, **kwargs).parse()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 885, in parse
    self._parse_no_numpy()
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/json/_json.py", line 1140, in _parse_no_numpy
    loads(json, precise_float=self.precise_float), dtype=None
ValueError: Expected object or value
[2022-07-08 21:59:28,694] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:59:28,719] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.324 seconds
[2022-07-08 21:59:58,797] {processor.py:153} INFO - Started process (PID=2083) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 21:59:58,811] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 21:59:58,811] {logging_mixin.py:115} INFO - [2022-07-08 21:59:58,811] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 21:59:59,118] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 21:59:59,142] {logging_mixin.py:115} INFO - [2022-07-08 21:59:59,142] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 21:59:59,166] {logging_mixin.py:115} INFO - [2022-07-08 21:59:59,166] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 21:59:59,201] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.408 seconds
[2022-07-08 22:00:29,284] {processor.py:153} INFO - Started process (PID=2129) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:00:29,293] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:00:29,293] {logging_mixin.py:115} INFO - [2022-07-08 22:00:29,293] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:00:29,576] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:00:29,598] {logging_mixin.py:115} INFO - [2022-07-08 22:00:29,598] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:00:29,621] {logging_mixin.py:115} INFO - [2022-07-08 22:00:29,621] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:00:29,637] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.358 seconds
[2022-07-08 22:00:59,711] {processor.py:153} INFO - Started process (PID=2156) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:00:59,712] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:00:59,712] {logging_mixin.py:115} INFO - [2022-07-08 22:00:59,712] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:01:00,023] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:01:00,049] {logging_mixin.py:115} INFO - [2022-07-08 22:01:00,049] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:01:00,074] {logging_mixin.py:115} INFO - [2022-07-08 22:01:00,074] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:01:00,132] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.424 seconds
[2022-07-08 22:01:01,721] {processor.py:153} INFO - Started process (PID=2160) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:01:01,722] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:01:01,723] {logging_mixin.py:115} INFO - [2022-07-08 22:01:01,722] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:01:02,020] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:01:02,042] {logging_mixin.py:115} INFO - [2022-07-08 22:01:02,042] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:01:02,064] {logging_mixin.py:115} INFO - [2022-07-08 22:01:02,064] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:01:02,089] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.372 seconds
[2022-07-08 22:01:32,168] {processor.py:153} INFO - Started process (PID=2180) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:01:32,176] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:01:32,176] {logging_mixin.py:115} INFO - [2022-07-08 22:01:32,176] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:01:32,453] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:01:32,475] {logging_mixin.py:115} INFO - [2022-07-08 22:01:32,474] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:01:32,496] {logging_mixin.py:115} INFO - [2022-07-08 22:01:32,495] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:01:32,514] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.351 seconds
[2022-07-08 22:02:02,591] {processor.py:153} INFO - Started process (PID=2209) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:02:02,600] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:02:02,601] {logging_mixin.py:115} INFO - [2022-07-08 22:02:02,601] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:02:02,906] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:02:02,930] {logging_mixin.py:115} INFO - [2022-07-08 22:02:02,929] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:02:02,953] {logging_mixin.py:115} INFO - [2022-07-08 22:02:02,953] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:02:03,006] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.420 seconds
[2022-07-08 22:02:33,087] {processor.py:153} INFO - Started process (PID=2238) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:02:33,088] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:02:33,089] {logging_mixin.py:115} INFO - [2022-07-08 22:02:33,089] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:02:33,404] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:02:33,428] {logging_mixin.py:115} INFO - [2022-07-08 22:02:33,428] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:02:33,451] {logging_mixin.py:115} INFO - [2022-07-08 22:02:33,451] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:02:33,482] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.400 seconds
[2022-07-08 22:02:52,544] {processor.py:153} INFO - Started process (PID=2249) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:02:52,558] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:02:52,558] {logging_mixin.py:115} INFO - [2022-07-08 22:02:52,558] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:02:52,872] {logging_mixin.py:115} INFO - [2022-07-08 22:02:52,871] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 38, in <module>
    api > load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 969, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): load_data>) is not an outlet
[2022-07-08 22:02:52,872] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:02:52,899] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.359 seconds
[2022-07-08 22:03:22,981] {processor.py:153} INFO - Started process (PID=2279) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:03:22,991] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:03:22,991] {logging_mixin.py:115} INFO - [2022-07-08 22:03:22,991] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:03:23,306] {logging_mixin.py:115} INFO - [2022-07-08 22:03:23,305] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 38, in <module>
    api > load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 969, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): load_data>) is not an outlet
[2022-07-08 22:03:23,306] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:03:23,341] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.364 seconds
[2022-07-08 22:03:53,416] {processor.py:153} INFO - Started process (PID=2308) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:03:53,432] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:03:53,432] {logging_mixin.py:115} INFO - [2022-07-08 22:03:53,432] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:03:53,736] {logging_mixin.py:115} INFO - [2022-07-08 22:03:53,735] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 38, in <module>
    api > load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 969, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): load_data>) is not an outlet
[2022-07-08 22:03:53,736] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:03:53,765] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.353 seconds
[2022-07-08 22:04:23,864] {processor.py:153} INFO - Started process (PID=2328) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:04:23,948] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:04:23,958] {logging_mixin.py:115} INFO - [2022-07-08 22:04:23,958] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:04:24,285] {logging_mixin.py:115} INFO - [2022-07-08 22:04:24,284] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 38, in <module>
    api > load
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 969, in __gt__
    raise TypeError(f"Left hand side ({obj}) is not an outlet")
TypeError: Left hand side (<Task(PythonOperator): load_data>) is not an outlet
[2022-07-08 22:04:24,285] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:04:24,331] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.472 seconds
[2022-07-08 22:04:51,399] {processor.py:153} INFO - Started process (PID=2356) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:04:51,414] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:04:51,415] {logging_mixin.py:115} INFO - [2022-07-08 22:04:51,415] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:04:51,721] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:04:51,747] {logging_mixin.py:115} INFO - [2022-07-08 22:04:51,746] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:04:51,768] {logging_mixin.py:115} INFO - [2022-07-08 22:04:51,768] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:04:51,831] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.438 seconds
[2022-07-08 22:05:21,918] {processor.py:153} INFO - Started process (PID=2384) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:05:22,012] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:05:22,013] {logging_mixin.py:115} INFO - [2022-07-08 22:05:22,013] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:05:22,321] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:05:22,343] {logging_mixin.py:115} INFO - [2022-07-08 22:05:22,343] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:05:22,363] {logging_mixin.py:115} INFO - [2022-07-08 22:05:22,363] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:05:22,382] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.469 seconds
[2022-07-08 22:05:52,463] {processor.py:153} INFO - Started process (PID=2413) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:05:52,472] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:05:52,472] {logging_mixin.py:115} INFO - [2022-07-08 22:05:52,472] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:05:52,803] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:05:52,828] {logging_mixin.py:115} INFO - [2022-07-08 22:05:52,827] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:05:52,849] {logging_mixin.py:115} INFO - [2022-07-08 22:05:52,849] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:05:52,873] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.414 seconds
[2022-07-08 22:06:22,948] {processor.py:153} INFO - Started process (PID=2439) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:06:22,963] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:06:22,964] {logging_mixin.py:115} INFO - [2022-07-08 22:06:22,964] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:06:23,263] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:06:23,284] {logging_mixin.py:115} INFO - [2022-07-08 22:06:23,283] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:06:23,307] {logging_mixin.py:115} INFO - [2022-07-08 22:06:23,307] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:06:23,345] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.399 seconds
[2022-07-08 22:06:53,438] {processor.py:153} INFO - Started process (PID=2461) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:06:53,438] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:06:53,439] {logging_mixin.py:115} INFO - [2022-07-08 22:06:53,439] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:06:53,742] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:06:53,773] {logging_mixin.py:115} INFO - [2022-07-08 22:06:53,772] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:06:53,794] {logging_mixin.py:115} INFO - [2022-07-08 22:06:53,794] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:06:53,813] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.379 seconds
[2022-07-08 22:07:23,897] {processor.py:153} INFO - Started process (PID=2492) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:07:23,897] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:07:23,898] {logging_mixin.py:115} INFO - [2022-07-08 22:07:23,898] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:07:24,216] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:07:24,239] {logging_mixin.py:115} INFO - [2022-07-08 22:07:24,239] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:07:24,261] {logging_mixin.py:115} INFO - [2022-07-08 22:07:24,261] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:07:24,280] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.388 seconds
[2022-07-08 22:07:54,360] {processor.py:153} INFO - Started process (PID=2517) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:07:54,520] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:07:54,558] {logging_mixin.py:115} INFO - [2022-07-08 22:07:54,558] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:07:54,867] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:07:54,885] {logging_mixin.py:115} INFO - [2022-07-08 22:07:54,885] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:07:54,907] {logging_mixin.py:115} INFO - [2022-07-08 22:07:54,907] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:07:54,932] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.576 seconds
[2022-07-08 22:08:25,031] {processor.py:153} INFO - Started process (PID=2546) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:08:25,032] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:08:25,032] {logging_mixin.py:115} INFO - [2022-07-08 22:08:25,032] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:08:25,359] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:08:25,384] {logging_mixin.py:115} INFO - [2022-07-08 22:08:25,383] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:08:25,406] {logging_mixin.py:115} INFO - [2022-07-08 22:08:25,406] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:08:25,425] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.398 seconds
[2022-07-08 22:08:55,507] {processor.py:153} INFO - Started process (PID=2579) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:08:55,528] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:08:55,528] {logging_mixin.py:115} INFO - [2022-07-08 22:08:55,528] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:08:55,831] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:08:55,855] {logging_mixin.py:115} INFO - [2022-07-08 22:08:55,855] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:08:55,884] {logging_mixin.py:115} INFO - [2022-07-08 22:08:55,884] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:08:55,908] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.407 seconds
[2022-07-08 22:09:25,988] {processor.py:153} INFO - Started process (PID=2603) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:09:26,002] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:09:26,003] {logging_mixin.py:115} INFO - [2022-07-08 22:09:26,003] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:09:26,321] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:09:26,340] {logging_mixin.py:115} INFO - [2022-07-08 22:09:26,340] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:09:26,369] {logging_mixin.py:115} INFO - [2022-07-08 22:09:26,369] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:09:26,397] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.413 seconds
[2022-07-08 22:09:56,474] {processor.py:153} INFO - Started process (PID=2632) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:09:56,485] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:09:56,486] {logging_mixin.py:115} INFO - [2022-07-08 22:09:56,485] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:09:56,777] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:09:56,799] {logging_mixin.py:115} INFO - [2022-07-08 22:09:56,799] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:09:56,820] {logging_mixin.py:115} INFO - [2022-07-08 22:09:56,820] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:09:56,843] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.374 seconds
[2022-07-08 22:10:26,926] {processor.py:153} INFO - Started process (PID=2665) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:10:26,943] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:10:26,944] {logging_mixin.py:115} INFO - [2022-07-08 22:10:26,944] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:10:27,256] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:10:27,277] {logging_mixin.py:115} INFO - [2022-07-08 22:10:27,276] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:10:27,300] {logging_mixin.py:115} INFO - [2022-07-08 22:10:27,299] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:10:27,330] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.409 seconds
[2022-07-08 22:10:57,410] {processor.py:153} INFO - Started process (PID=2689) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:10:57,417] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:10:57,418] {logging_mixin.py:115} INFO - [2022-07-08 22:10:57,418] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:10:57,703] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:10:57,725] {logging_mixin.py:115} INFO - [2022-07-08 22:10:57,725] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:10:57,745] {logging_mixin.py:115} INFO - [2022-07-08 22:10:57,745] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:10:57,771] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.365 seconds
[2022-07-08 22:11:27,846] {processor.py:153} INFO - Started process (PID=2718) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:11:27,867] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:11:27,868] {logging_mixin.py:115} INFO - [2022-07-08 22:11:27,868] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:11:28,157] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:11:28,180] {logging_mixin.py:115} INFO - [2022-07-08 22:11:28,179] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:11:28,200] {logging_mixin.py:115} INFO - [2022-07-08 22:11:28,200] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:11:28,222] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.380 seconds
[2022-07-08 22:11:58,264] {processor.py:153} INFO - Started process (PID=2749) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:11:58,275] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:11:58,276] {logging_mixin.py:115} INFO - [2022-07-08 22:11:58,276] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:11:58,592] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:11:58,616] {logging_mixin.py:115} INFO - [2022-07-08 22:11:58,615] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:11:58,637] {logging_mixin.py:115} INFO - [2022-07-08 22:11:58,636] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:11:58,707] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.445 seconds
[2022-07-08 22:12:29,341] {processor.py:153} INFO - Started process (PID=2771) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:12:29,341] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:12:29,342] {logging_mixin.py:115} INFO - [2022-07-08 22:12:29,342] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:12:29,611] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:12:29,635] {logging_mixin.py:115} INFO - [2022-07-08 22:12:29,634] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:12:29,655] {logging_mixin.py:115} INFO - [2022-07-08 22:12:29,655] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:12:29,678] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.341 seconds
[2022-07-08 22:12:59,762] {processor.py:153} INFO - Started process (PID=2806) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:12:59,788] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:12:59,789] {logging_mixin.py:115} INFO - [2022-07-08 22:12:59,789] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:13:00,078] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:13:00,105] {logging_mixin.py:115} INFO - [2022-07-08 22:13:00,105] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:13:00,126] {logging_mixin.py:115} INFO - [2022-07-08 22:13:00,126] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:13:00,149] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.392 seconds
[2022-07-08 22:13:30,229] {processor.py:153} INFO - Started process (PID=2837) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:13:30,240] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:13:30,240] {logging_mixin.py:115} INFO - [2022-07-08 22:13:30,240] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:13:30,567] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:13:30,633] {logging_mixin.py:115} INFO - [2022-07-08 22:13:30,632] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:13:30,654] {logging_mixin.py:115} INFO - [2022-07-08 22:13:30,654] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:13:30,751] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.527 seconds
[2022-07-08 22:14:00,832] {processor.py:153} INFO - Started process (PID=2859) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:14:00,832] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:14:00,833] {logging_mixin.py:115} INFO - [2022-07-08 22:14:00,833] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:14:01,128] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:14:01,150] {logging_mixin.py:115} INFO - [2022-07-08 22:14:01,150] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:14:01,170] {logging_mixin.py:115} INFO - [2022-07-08 22:14:01,170] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:14:01,189] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.360 seconds
[2022-07-08 22:14:31,278] {processor.py:153} INFO - Started process (PID=2895) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:14:31,287] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:14:31,288] {logging_mixin.py:115} INFO - [2022-07-08 22:14:31,287] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:14:31,594] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:14:31,617] {logging_mixin.py:115} INFO - [2022-07-08 22:14:31,617] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:14:31,642] {logging_mixin.py:115} INFO - [2022-07-08 22:14:31,642] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:14:31,668] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.395 seconds
[2022-07-08 22:15:01,692] {processor.py:153} INFO - Started process (PID=2926) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:15:01,703] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:15:01,704] {logging_mixin.py:115} INFO - [2022-07-08 22:15:01,704] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:15:01,978] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:15:02,000] {logging_mixin.py:115} INFO - [2022-07-08 22:15:01,999] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:15:02,021] {logging_mixin.py:115} INFO - [2022-07-08 22:15:02,021] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:15:02,042] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.354 seconds
[2022-07-08 22:15:32,082] {processor.py:153} INFO - Started process (PID=2948) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:15:32,083] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:15:32,084] {logging_mixin.py:115} INFO - [2022-07-08 22:15:32,084] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:15:32,394] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:15:32,417] {logging_mixin.py:115} INFO - [2022-07-08 22:15:32,417] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:15:32,438] {logging_mixin.py:115} INFO - [2022-07-08 22:15:32,437] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:15:32,447] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.369 seconds
[2022-07-08 22:16:02,507] {processor.py:153} INFO - Started process (PID=2979) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:16:02,527] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:16:02,528] {logging_mixin.py:115} INFO - [2022-07-08 22:16:02,528] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:16:02,813] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:16:02,839] {logging_mixin.py:115} INFO - [2022-07-08 22:16:02,838] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:16:02,868] {logging_mixin.py:115} INFO - [2022-07-08 22:16:02,867] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:16:02,892] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.389 seconds
[2022-07-08 22:16:32,940] {processor.py:153} INFO - Started process (PID=3002) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:16:32,952] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:16:32,953] {logging_mixin.py:115} INFO - [2022-07-08 22:16:32,953] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:16:33,298] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:16:33,324] {logging_mixin.py:115} INFO - [2022-07-08 22:16:33,323] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:16:33,345] {logging_mixin.py:115} INFO - [2022-07-08 22:16:33,345] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:16:33,376] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.440 seconds
[2022-07-08 22:17:04,027] {processor.py:153} INFO - Started process (PID=3034) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:17:04,028] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:17:04,028] {logging_mixin.py:115} INFO - [2022-07-08 22:17:04,028] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:17:04,333] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:17:04,359] {logging_mixin.py:115} INFO - [2022-07-08 22:17:04,358] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:17:04,379] {logging_mixin.py:115} INFO - [2022-07-08 22:17:04,379] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:17:04,400] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.377 seconds
[2022-07-08 22:17:34,484] {processor.py:153} INFO - Started process (PID=3066) to work on /opt/airflow/dags/test-dag.py
[2022-07-08 22:17:34,492] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-07-08 22:17:34,493] {logging_mixin.py:115} INFO - [2022-07-08 22:17:34,493] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-07-08 22:17:34,814] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-07-08 22:17:34,836] {logging_mixin.py:115} INFO - [2022-07-08 22:17:34,836] {dag.py:2379} INFO - Sync 1 DAGs
[2022-07-08 22:17:34,867] {logging_mixin.py:115} INFO - [2022-07-08 22:17:34,867] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-07-08T00:00:00+00:00, run_after=2022-07-09T00:00:00+00:00
[2022-07-08 22:17:34,889] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.410 seconds
