[2022-06-29 01:23:56,471] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl manual__2022-06-29T01:17:27.236388+00:00 [queued]>
[2022-06-29 01:23:56,489] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl manual__2022-06-29T01:17:27.236388+00:00 [queued]>
[2022-06-29 01:23:56,489] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-29 01:23:56,489] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-06-29 01:23:56,489] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-29 01:23:56,518] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): my_etl> on 2022-06-29 01:17:27.236388+00:00
[2022-06-29 01:23:56,525] {standard_task_runner.py:52} INFO - Started process 89 to run task
[2022-06-29 01:23:56,529] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'my_etl', 'manual__2022-06-29T01:17:27.236388+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/test-dag.py', '--cfg-path', '/tmp/tmpgbs6ea5p', '--error-file', '/tmp/tmpf82fgq4b']
[2022-06-29 01:23:56,530] {standard_task_runner.py:80} INFO - Job 357: Subtask my_etl
[2022-06-29 01:23:56,607] {task_command.py:370} INFO - Running <TaskInstance: test.my_etl manual__2022-06-29T01:17:27.236388+00:00 [running]> on host 3c0196e07a8e
[2022-06-29 01:23:56,926] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=my_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-06-29T01:17:27.236388+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-29T01:17:27.236388+00:00
[2022-06-29 01:24:05,792] {python.py:173} INFO - Done. Returned value was: None
[2022-06-29 01:24:05,814] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=my_etl, execution_date=20220629T011727, start_date=20220629T012356, end_date=20220629T012405
[2022-06-29 01:24:05,869] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-29 01:24:05,935] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
