[2022-06-29 01:23:56,378] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl manual__2022-06-24T07:22:49.166391+00:00 [queued]>
[2022-06-29 01:23:56,391] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: test.my_etl manual__2022-06-24T07:22:49.166391+00:00 [queued]>
[2022-06-29 01:23:56,391] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-06-29 01:23:56,391] {taskinstance.py:1357} INFO - Starting attempt 2 of 2
[2022-06-29 01:23:56,391] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-06-29 01:23:56,459] {taskinstance.py:1377} INFO - Executing <Task(PythonOperator): my_etl> on 2022-06-24 07:22:49.166391+00:00
[2022-06-29 01:23:56,467] {standard_task_runner.py:52} INFO - Started process 84 to run task
[2022-06-29 01:23:56,472] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'test', 'my_etl', 'manual__2022-06-24T07:22:49.166391+00:00', '--job-id', '352', '--raw', '--subdir', 'DAGS_FOLDER/test-dag.py', '--cfg-path', '/tmp/tmp5au89gys', '--error-file', '/tmp/tmpmvrfpci6']
[2022-06-29 01:23:56,474] {standard_task_runner.py:80} INFO - Job 352: Subtask my_etl
[2022-06-29 01:23:56,552] {task_command.py:370} INFO - Running <TaskInstance: test.my_etl manual__2022-06-24T07:22:49.166391+00:00 [running]> on host 3c0196e07a8e
[2022-06-29 01:23:56,926] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=test
AIRFLOW_CTX_TASK_ID=my_etl
AIRFLOW_CTX_EXECUTION_DATE=2022-06-24T07:22:49.166391+00:00
AIRFLOW_CTX_TRY_NUMBER=2
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-06-24T07:22:49.166391+00:00
[2022-06-29 01:24:06,259] {python.py:173} INFO - Done. Returned value was: None
[2022-06-29 01:24:06,280] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=test, task_id=my_etl, execution_date=20220624T072249, start_date=20220629T012356, end_date=20220629T012406
[2022-06-29 01:24:06,317] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-06-29 01:24:06,369] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
