[2022-06-14 19:36:59,142] {processor.py:153} INFO - Started process (PID=6900) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:36:59,142] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:36:59,143] {logging_mixin.py:115} INFO - [2022-06-14 19:36:59,143] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:36:59,144] {logging_mixin.py:115} INFO - [2022-06-14 19:36:59,144] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:36:59,144] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:36:59,288] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.148 seconds
[2022-06-14 19:37:29,536] {processor.py:153} INFO - Started process (PID=6953) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:37:29,554] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:37:29,554] {logging_mixin.py:115} INFO - [2022-06-14 19:37:29,554] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:37:29,556] {logging_mixin.py:115} INFO - [2022-06-14 19:37:29,555] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:37:29,556] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:37:29,680] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.147 seconds
[2022-06-14 19:38:00,432] {processor.py:153} INFO - Started process (PID=7015) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:38:00,432] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:38:00,432] {logging_mixin.py:115} INFO - [2022-06-14 19:38:00,432] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:38:00,433] {logging_mixin.py:115} INFO - [2022-06-14 19:38:00,433] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:38:00,434] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:38:00,563] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.135 seconds
[2022-06-14 19:38:31,191] {processor.py:153} INFO - Started process (PID=7077) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:38:31,203] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:38:31,204] {logging_mixin.py:115} INFO - [2022-06-14 19:38:31,204] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:38:31,207] {logging_mixin.py:115} INFO - [2022-06-14 19:38:31,206] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:38:31,207] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:38:31,330] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.141 seconds
[2022-06-14 19:39:01,490] {processor.py:153} INFO - Started process (PID=7130) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:39:01,504] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:39:01,504] {logging_mixin.py:115} INFO - [2022-06-14 19:39:01,504] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:39:01,505] {logging_mixin.py:115} INFO - [2022-06-14 19:39:01,505] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:39:01,506] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:39:01,622] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.136 seconds
[2022-06-14 19:39:32,099] {processor.py:153} INFO - Started process (PID=7192) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:39:32,102] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:39:32,102] {logging_mixin.py:115} INFO - [2022-06-14 19:39:32,102] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:39:32,104] {logging_mixin.py:115} INFO - [2022-06-14 19:39:32,103] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:39:32,104] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:39:32,229] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.134 seconds
[2022-06-14 19:40:02,778] {processor.py:153} INFO - Started process (PID=7254) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:40:02,779] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:40:02,779] {logging_mixin.py:115} INFO - [2022-06-14 19:40:02,779] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:40:02,780] {logging_mixin.py:115} INFO - [2022-06-14 19:40:02,780] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:40:02,780] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:40:02,913] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.138 seconds
[2022-06-14 19:40:33,217] {processor.py:153} INFO - Started process (PID=7307) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:40:33,217] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:40:33,218] {logging_mixin.py:115} INFO - [2022-06-14 19:40:33,218] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:40:33,221] {logging_mixin.py:115} INFO - [2022-06-14 19:40:33,220] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:40:33,221] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:40:33,337] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.125 seconds
[2022-06-14 19:41:03,726] {processor.py:153} INFO - Started process (PID=7369) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:41:03,736] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:41:03,736] {logging_mixin.py:115} INFO - [2022-06-14 19:41:03,736] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:41:03,737] {logging_mixin.py:115} INFO - [2022-06-14 19:41:03,737] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:41:03,737] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:41:03,862] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.143 seconds
[2022-06-14 19:41:34,244] {processor.py:153} INFO - Started process (PID=7431) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:41:34,244] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:41:34,245] {logging_mixin.py:115} INFO - [2022-06-14 19:41:34,245] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:41:34,247] {logging_mixin.py:115} INFO - [2022-06-14 19:41:34,246] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:41:34,248] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:41:34,379] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.139 seconds
[2022-06-14 19:42:04,684] {processor.py:153} INFO - Started process (PID=7484) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:42:04,685] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:42:04,685] {logging_mixin.py:115} INFO - [2022-06-14 19:42:04,685] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:42:04,686] {logging_mixin.py:115} INFO - [2022-06-14 19:42:04,686] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:42:04,686] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:42:04,711] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.032 seconds
[2022-06-14 19:42:35,588] {processor.py:153} INFO - Started process (PID=7546) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:42:35,601] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:42:35,601] {logging_mixin.py:115} INFO - [2022-06-14 19:42:35,601] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:42:35,604] {logging_mixin.py:115} INFO - [2022-06-14 19:42:35,602] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:42:35,604] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:42:35,637] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.052 seconds
[2022-06-14 19:43:06,512] {processor.py:153} INFO - Started process (PID=7608) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:43:06,512] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:43:06,513] {logging_mixin.py:115} INFO - [2022-06-14 19:43:06,513] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:43:06,516] {logging_mixin.py:115} INFO - [2022-06-14 19:43:06,515] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:43:06,516] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:43:06,544] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.037 seconds
[2022-06-14 19:43:37,203] {processor.py:153} INFO - Started process (PID=7661) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:43:37,217] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:43:37,217] {logging_mixin.py:115} INFO - [2022-06-14 19:43:37,217] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:43:37,218] {logging_mixin.py:115} INFO - [2022-06-14 19:43:37,218] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:43:37,218] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:43:37,254] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.054 seconds
[2022-06-14 19:44:07,986] {processor.py:153} INFO - Started process (PID=7723) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:44:07,987] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:44:07,988] {logging_mixin.py:115} INFO - [2022-06-14 19:44:07,987] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:44:07,990] {logging_mixin.py:115} INFO - [2022-06-14 19:44:07,989] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:44:07,991] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:44:08,028] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.046 seconds
[2022-06-14 19:44:38,943] {processor.py:153} INFO - Started process (PID=7785) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:44:38,957] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:44:38,958] {logging_mixin.py:115} INFO - [2022-06-14 19:44:38,958] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:44:38,959] {logging_mixin.py:115} INFO - [2022-06-14 19:44:38,958] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:44:38,960] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:44:38,995] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.056 seconds
[2022-06-14 19:45:09,848] {processor.py:153} INFO - Started process (PID=7838) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:45:09,922] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:45:09,923] {logging_mixin.py:115} INFO - [2022-06-14 19:45:09,923] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:45:09,925] {logging_mixin.py:115} INFO - [2022-06-14 19:45:09,924] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:45:09,926] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:45:10,011] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.167 seconds
[2022-06-14 19:45:40,621] {processor.py:153} INFO - Started process (PID=7900) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:45:40,622] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:45:40,622] {logging_mixin.py:115} INFO - [2022-06-14 19:45:40,622] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:45:40,625] {logging_mixin.py:115} INFO - [2022-06-14 19:45:40,624] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:45:40,625] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:45:40,660] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.043 seconds
[2022-06-14 19:46:11,468] {processor.py:153} INFO - Started process (PID=7962) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:46:11,481] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:46:11,481] {logging_mixin.py:115} INFO - [2022-06-14 19:46:11,481] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:46:11,483] {logging_mixin.py:115} INFO - [2022-06-14 19:46:11,482] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:46:11,484] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:46:11,519] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.055 seconds
[2022-06-14 19:46:42,214] {processor.py:153} INFO - Started process (PID=8015) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:46:42,214] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:46:42,215] {logging_mixin.py:115} INFO - [2022-06-14 19:46:42,215] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:46:42,218] {logging_mixin.py:115} INFO - [2022-06-14 19:46:42,216] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:46:42,218] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:46:42,243] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.034 seconds
[2022-06-14 19:47:12,987] {processor.py:153} INFO - Started process (PID=8077) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:47:12,998] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:47:12,999] {logging_mixin.py:115} INFO - [2022-06-14 19:47:12,999] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:47:13,001] {logging_mixin.py:115} INFO - [2022-06-14 19:47:13,000] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:47:13,002] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:47:13,043] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.061 seconds
[2022-06-14 19:47:43,885] {processor.py:153} INFO - Started process (PID=8139) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:47:43,885] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:47:43,886] {logging_mixin.py:115} INFO - [2022-06-14 19:47:43,886] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:47:43,889] {logging_mixin.py:115} INFO - [2022-06-14 19:47:43,888] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:47:43,889] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:47:43,917] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.037 seconds
[2022-06-14 19:48:14,687] {processor.py:153} INFO - Started process (PID=8198) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:48:14,697] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:48:14,698] {logging_mixin.py:115} INFO - [2022-06-14 19:48:14,698] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:48:14,701] {logging_mixin.py:115} INFO - [2022-06-14 19:48:14,700] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:48:14,701] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:48:14,780] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.098 seconds
[2022-06-14 19:48:44,866] {processor.py:153} INFO - Started process (PID=8254) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:48:44,866] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:48:44,867] {logging_mixin.py:115} INFO - [2022-06-14 19:48:44,867] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:48:44,870] {logging_mixin.py:115} INFO - [2022-06-14 19:48:44,869] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:48:44,870] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:48:44,901] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.040 seconds
[2022-06-14 19:49:15,759] {processor.py:153} INFO - Started process (PID=8316) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:49:15,760] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:49:15,761] {logging_mixin.py:115} INFO - [2022-06-14 19:49:15,761] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:49:15,763] {logging_mixin.py:115} INFO - [2022-06-14 19:49:15,762] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:49:15,763] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:49:15,793] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.038 seconds
[2022-06-14 19:49:46,644] {processor.py:153} INFO - Started process (PID=8369) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:49:46,645] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:49:46,646] {logging_mixin.py:115} INFO - [2022-06-14 19:49:46,646] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:49:46,649] {logging_mixin.py:115} INFO - [2022-06-14 19:49:46,647] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:49:46,649] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:49:46,676] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.035 seconds
[2022-06-14 19:50:16,792] {processor.py:153} INFO - Started process (PID=8431) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:50:16,796] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:50:16,797] {logging_mixin.py:115} INFO - [2022-06-14 19:50:16,797] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:50:16,800] {logging_mixin.py:115} INFO - [2022-06-14 19:50:16,799] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:50:16,800] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:50:16,863] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.075 seconds
[2022-06-14 19:50:46,940] {processor.py:153} INFO - Started process (PID=8493) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:50:46,940] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:50:46,941] {logging_mixin.py:115} INFO - [2022-06-14 19:50:46,941] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:50:46,942] {logging_mixin.py:115} INFO - [2022-06-14 19:50:46,942] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:50:46,942] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:50:46,976] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.040 seconds
[2022-06-14 19:51:17,283] {processor.py:153} INFO - Started process (PID=8546) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:51:17,283] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:51:17,283] {logging_mixin.py:115} INFO - [2022-06-14 19:51:17,283] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:51:17,285] {logging_mixin.py:115} INFO - [2022-06-14 19:51:17,284] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:51:17,285] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:51:17,317] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.038 seconds
[2022-06-14 19:51:47,439] {processor.py:153} INFO - Started process (PID=8608) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:51:47,440] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:51:47,441] {logging_mixin.py:115} INFO - [2022-06-14 19:51:47,441] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:51:47,443] {logging_mixin.py:115} INFO - [2022-06-14 19:51:47,443] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:51:47,443] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:51:47,466] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.031 seconds
[2022-06-14 19:52:17,815] {processor.py:153} INFO - Started process (PID=8670) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:52:17,816] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:52:17,817] {logging_mixin.py:115} INFO - [2022-06-14 19:52:17,817] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:52:17,819] {logging_mixin.py:115} INFO - [2022-06-14 19:52:17,819] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 3
    with DAG()
             ^
SyntaxError: invalid syntax
[2022-06-14 19:52:17,819] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:52:17,850] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.039 seconds
[2022-06-14 19:52:48,026] {processor.py:153} INFO - Started process (PID=8723) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:52:48,026] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:52:48,027] {logging_mixin.py:115} INFO - [2022-06-14 19:52:48,027] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:52:48,029] {logging_mixin.py:115} INFO - [2022-06-14 19:52:48,028] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 16
    default_args=default_args
               ^
SyntaxError: invalid syntax
[2022-06-14 19:52:48,030] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:52:48,058] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.036 seconds
[2022-06-14 19:52:59,020] {processor.py:153} INFO - Started process (PID=8765) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:52:59,020] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:52:59,021] {logging_mixin.py:115} INFO - [2022-06-14 19:52:59,021] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:52:59,023] {logging_mixin.py:115} INFO - [2022-06-14 19:52:59,022] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 16
    default_args=default_args
               ^
SyntaxError: invalid syntax
[2022-06-14 19:52:59,024] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:52:59,058] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.043 seconds
[2022-06-14 19:54:25,065] {processor.py:153} INFO - Started process (PID=41) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:54:25,078] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:54:25,078] {logging_mixin.py:115} INFO - [2022-06-14 19:54:25,078] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:54:25,080] {logging_mixin.py:115} INFO - [2022-06-14 19:54:25,079] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 16
    default_args=default_args
               ^
SyntaxError: invalid syntax
[2022-06-14 19:54:25,080] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:54:25,159] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.097 seconds
[2022-06-14 19:54:55,432] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:54:55,446] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:54:55,446] {logging_mixin.py:115} INFO - [2022-06-14 19:54:55,446] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:54:55,447] {logging_mixin.py:115} INFO - [2022-06-14 19:54:55,447] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 16
    default_args=default_args
               ^
SyntaxError: invalid syntax
[2022-06-14 19:54:55,447] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:54:55,493] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.066 seconds
[2022-06-14 19:55:25,936] {processor.py:153} INFO - Started process (PID=156) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:55:25,945] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:55:25,946] {logging_mixin.py:115} INFO - [2022-06-14 19:55:25,946] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:55:25,947] {logging_mixin.py:115} INFO - [2022-06-14 19:55:25,946] {dagbag.py:320} ERROR - Failed to import: /opt/airflow/dags/test-dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 317, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 724, in exec_module
  File "<frozen importlib._bootstrap_external>", line 860, in get_code
  File "<frozen importlib._bootstrap_external>", line 791, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/test-dag.py", line 16
    default_args=default_args
               ^
SyntaxError: invalid syntax
[2022-06-14 19:55:25,947] {processor.py:653} WARNING - No viable dags retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:55:25,984] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.052 seconds
[2022-06-14 19:55:49,322] {processor.py:153} INFO - Started process (PID=209) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:55:49,337] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:55:49,337] {logging_mixin.py:115} INFO - [2022-06-14 19:55:49,337] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:55:49,348] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:55:49,450] {logging_mixin.py:115} INFO - [2022-06-14 19:55:49,450] {manager.py:508} INFO - Created Permission View: can edit on DAG:test
[2022-06-14 19:55:49,467] {logging_mixin.py:115} INFO - [2022-06-14 19:55:49,467] {manager.py:508} INFO - Created Permission View: can read on DAG:test
[2022-06-14 19:55:49,484] {logging_mixin.py:115} INFO - [2022-06-14 19:55:49,484] {manager.py:508} INFO - Created Permission View: can delete on DAG:test
[2022-06-14 19:55:49,484] {logging_mixin.py:115} INFO - [2022-06-14 19:55:49,484] {dag.py:2379} INFO - Sync 1 DAGs
[2022-06-14 19:55:49,494] {logging_mixin.py:115} INFO - [2022-06-14 19:55:49,494] {dag.py:2398} INFO - Creating ORM DAG for test
[2022-06-14 19:55:49,591] {logging_mixin.py:115} INFO - [2022-06-14 19:55:49,590] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-15T00:00:00+00:00, run_after=2022-06-16T00:00:00+00:00
[2022-06-14 19:55:49,609] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.291 seconds
[2022-06-14 19:57:05,388] {processor.py:153} INFO - Started process (PID=41) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:57:05,403] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:57:05,403] {logging_mixin.py:115} INFO - [2022-06-14 19:57:05,403] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:57:05,417] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:57:05,447] {logging_mixin.py:115} INFO - [2022-06-14 19:57:05,447] {dag.py:2379} INFO - Sync 1 DAGs
[2022-06-14 19:57:05,475] {logging_mixin.py:115} INFO - [2022-06-14 19:57:05,474] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-15T00:00:00+00:00, run_after=2022-06-16T00:00:00+00:00
[2022-06-14 19:57:05,498] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.116 seconds
[2022-06-14 19:57:35,915] {processor.py:153} INFO - Started process (PID=103) to work on /opt/airflow/dags/test-dag.py
[2022-06-14 19:57:35,916] {processor.py:641} INFO - Processing file /opt/airflow/dags/test-dag.py for tasks to queue
[2022-06-14 19:57:35,917] {logging_mixin.py:115} INFO - [2022-06-14 19:57:35,917] {dagbag.py:507} INFO - Filling up the DagBag from /opt/airflow/dags/test-dag.py
[2022-06-14 19:57:35,926] {processor.py:651} INFO - DAG(s) dict_keys(['test']) retrieved from /opt/airflow/dags/test-dag.py
[2022-06-14 19:57:35,950] {logging_mixin.py:115} INFO - [2022-06-14 19:57:35,950] {dag.py:2379} INFO - Sync 1 DAGs
[2022-06-14 19:57:35,974] {logging_mixin.py:115} INFO - [2022-06-14 19:57:35,973] {dag.py:2931} INFO - Setting next_dagrun for test to 2022-06-15T00:00:00+00:00, run_after=2022-06-16T00:00:00+00:00
[2022-06-14 19:57:35,999] {processor.py:161} INFO - Processing /opt/airflow/dags/test-dag.py took 0.088 seconds
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           